version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: yarn run start:dev
    env_file:
      - .env
    networks:
      - kwanwoo
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - kwanwoo
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
networks:
  kwanwoo:
volumes:
  mysql_data:
